// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('create a account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('create a account', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(4) > .RuiSidebar-listItem-82 > .MuiListItemText-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButton-label"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-label")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("member-form-name")).click()
    await driver.findElement(By.id("member-form-name")).sendKeys("junaid")
    await driver.findElement(By.id("member-form-email")).sendKeys("junaid16586@gmail.com")
    await driver.findElement(By.css(".btn-primary > span")).click()
  })
})
