// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('filter tag', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('filter tag', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    {
      const element = await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(3) > .RuiSidebar-listItem-82 > .MuiListItemText-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(3) > .RuiSidebar-listItem-82 > .MuiListItemText-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.name("filterInput")).click()
    await driver.findElement(By.name("filterInput")).sendKeys("shoes")
  })
})
