// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('new group', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('new group', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(1299, 741)
    {
      const element = await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(4) > .RuiSidebar-listItem-82 > .MuiListItemText-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(4) > .RuiSidebar-listItem-82 > .MuiListItemText-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    await driver.findElement(By.css(".fa-plus")).click()
    await driver.findElement(By.id("add-group-name")).click()
    await driver.findElement(By.id("add-group-name")).sendKeys("retailer")
    await driver.findElement(By.id("add-group-description")).sendKeys("retailer")
    await driver.findElement(By.css(".justify:nth-child(3) span")).click()
    {
      const element = await driver.findElement(By.css(".justify:nth-child(3) span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
