// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Remove an account', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Remove an account', async function() {
    await driver.get("http://localhost:3000/operator")
    await driver.manage().window().setRect(811, 555)
    {
      const element = await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(4) > .RuiSidebar-listItem-82 > .MuiListItemText-root > span"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".RuiSidebar-link-85:nth-child(4) > .RuiSidebar-listItem-82 > .MuiListItemText-root > span")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiButton-root")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn-danger > span")).click()
    await driver.findElement(By.css(".swal2-confirm")).click()
  })
})
